# Generated by Django 4.2 on 2025-01-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_movie', models.CharField(max_length=30)),
                ('genero_movie', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('sinopsis', models.TextField(max_length=500)),
            ],
        ),
    ]
